// src/client/pages/Test.vue
<template>
  <div>
    <h1 class="text-2xl font-bold mb-4">Test Page</h1>
    <div class="space-x-4">
      <Button @click="run">Run</Button>
      <Button @click="stream">Stream</Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Button } from "@/components/ui/button";

const stream = async () => {
  console.log("stream");
  const url = "http://localhost:8085/api/mulmo/123/stream?" + Date.now();
  const response = await fetch(url, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  if (!response.ok) {
    throw new Error(`HTTP error! status: ${response.status}`);
  }
  console.log(await response.json());
};

const run = async () => {
  const url = "http://localhost:8085/api/mulmo/123/run";
  const data = {};
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });
  if (!response.ok) {
    throw new Error(`HTTP error! status: ${response.status}`);
  }
  console.log(await response.json());
};
</script>

// src/react/test.tsx
import React from "react";

const stream = async () => {
  console.log("stream");
  const url = "http://localhost:8085/api/mulmo/123/stream?" + Date.now();
  const data = {};
  const response = await fetch(url, {
    // method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    // body: JSON.stringify(data),
  });
  if (!response.ok) {
    throw new Error(`HTTP error! status: ${response.status}`);
  }
  console.log(await response.json());
};

const run = async () => {
  const url = "http://localhost:8085/api/mulmo/123/run";
  const data = {};
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });
  if (!response.ok) {
    throw new Error(`HTTP error! status: ${response.status}`);
  }
  console.log(await response.json());
};

const Home: React.FC = () => {
  return (
    <>
      <h2>Text</h2>
      <button onClick={run}>run</button>
      <button onClick={stream}>stream</button>
    </>
  );
};

export default Home;
